//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWcompleteScaff.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class User
    {
        public int UserID { get; set; }
        
        [DisplayName("User Name")]
        [Required(ErrorMessage = "User Name is required.")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }

        /* Hello :) Above are some additions in the model class made with entity framework
        for showing User Name nicely, not like in the database, and password shown in the input field with dots,
        not the actual text written by
        the login candidate. */
    }
}
